name: Security Scan (Semgrep)

on:
  push:
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Debug files
        run: ls -R

      - name: Install Semgrep
        run: |
          python3 -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep scan
        run: semgrep --config=auto webapp || true

      - name: Save results
        run: semgrep --config=auto webapp --json --output=semgrep-results.json

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep-results.json